// Consolidate SA campaign results into the thesis tables. Tolerant of missing files
// (the campaign writes results incrementally) — reports whatever is present.
//   node scripts/sa/summarize.mjs [--set reduced] [--points term_neonate,pphn,cdh_severe]
//
// Emits, per operating point:
//   - one-lever DOMINANCE (OAT top influence vs designated lever)
//   - Morris mu* ranking + interaction (sigma/mu*) flag
//   - Sobol one-lever validation: S_i(designated), is-max, S_i vs S_Ti, interaction budget, CI
//   - PRCC sign/magnitude for the designated lever
//   - identifiability: FIM condition number + QR ordering
// and a compact machine-readable JSON to results/_summary.json.

import fs from "node:fs";
import { DESIGNATED, OUTPUTS } from "./_sa_params.mjs";

const arg = (n, d) => { const i = process.argv.indexOf(n); return i >= 0 ? process.argv[i + 1] : d; };
const set = arg("--set", "reduced");
const points = arg("--points", "term_neonate,pphn,cdh_severe,dtga,hlhs").split(",");
const R = (s, t) => new URL(`./results/${s}_${t}_${set}.json`, import.meta.url).pathname;
const load = (p) => (fs.existsSync(p) ? JSON.parse(fs.readFileSync(p, "utf8")) : null);
const targets = Object.keys(DESIGNATED);

const summary = {};
for (const s of points) {
  const oat = load(R(s, "oat")), morris = load(R(s, "morris")), sobol = load(R(s, "sobol")), prcc = load(R(s, "prcc"));
  if (!oat && !morris && !sobol && !prcc) continue;
  console.error(`\n============================ ${s} ============================`);
  const rec = { oat: !!oat, morris: !!morris, sobol: !!sobol, prcc: !!prcc, targets: {} };

  if (oat) {
    const b = oat.result.baseline;
    console.error(`baseline: MAP ${f(b.map)} PAP ${f(b.pap_m)} CO ${f(b.co,2)} SpO2 ${f(b.spo2)} PaO2 ${f(b.po2)} PaCO2 ${f(b.pco2)} pH ${f(b.ph,2)} BE ${f(b.be)} CVP ${f(b.cvp)} q_da ${f(b.q_da)} q_fo ${f(b.q_fo)}`);
    console.error(`identifiability: FIM condition = ${oat.result.identifiability.condition.toExponential(2)}   (boundary-inactive: ${(oat.result.boundaryInactive||[]).join(", ")||"none"})`);
    console.error(`  QR identifiability order: ${oat.result.identifiability.qrOrder.map(q=>q.param).join(" > ")}`);
    rec.identifiability = oat.result.identifiability;
  }

  console.error(`\n${"target".padEnd(7)}${"designated".padEnd(15)}${"OAT top".padEnd(15)}${"S_i(des)".padStart(9)}${"maxS_i".padStart(9)}${"S_Ti(des)".padStart(10)}${"PRCC".padStart(8)}   verdict`);
  for (const t of targets) {
    const des = DESIGNATED[t];
    const params = (oat || morris || sobol || prcc).params;
    const di = params.indexOf(des);
    const row = { designated: des };
    // OAT top
    let oatTop = "-";
    if (oat) {
      const cells = oat.result.elasticities[t];
      if (cells) { let mj=-1,mv=0; cells.forEach((c,j)=>{if(Number.isFinite(c.normSens)&&Math.abs(c.normSens)>Math.abs(mv)){mv=c.normSens;mj=j;}}); oatTop = mj>=0?params[mj]:"-"; row.oatTop=oatTop; }
    }
    // Sobol
    let Sdes=NaN, Smax=NaN, STdes=NaN, sMaxParam="-", isMax=false;
    if (sobol && sobol.result.sobol[t] && sobol.result.sobol[t].indices) {
      const ind = sobol.result.sobol[t].indices;
      const dind = ind[di];
      Sdes = dind?.Si; STdes = dind?.STi;
      let mj=-1,mv=-Infinity; ind.forEach((x,j)=>{if(x.Si>mv){mv=x.Si;mj=j;}}); Smax=mv; sMaxParam=params[mj]; isMax=(mj===di);
      row.sobol={Si:Sdes,STi:STdes,SiMaxParam:sMaxParam,isMax,interaction:STdes-Sdes,CI:dind?.SiCI};
    }
    // PRCC
    let pc=NaN;
    if (prcc && Array.isArray(prcc.result.prcc[t])) { pc = prcc.result.prcc[t][di]?.prcc; row.prcc=pc; }
    // verdict (only meaningful with sobol)
    let verdict="";
    if (sobol && Number.isFinite(Sdes)) {
      const dominant = isMax; const decoupled = Number.isFinite(STdes) && (STdes-Sdes) < 0.15;
      verdict = dominant ? (decoupled ? "ONE-LEVER OK" : "dominant, interacting") : `dominated by ${sMaxParam}`;
    } else if (oat) verdict = oatTop===des ? "OAT-dominant" : `OAT top ${oatTop}`;
    row.verdict = verdict;
    rec.targets[t] = row;
    console.error(`${t.padEnd(7)}${String(des).padEnd(15)}${String(oatTop).padEnd(15)}${fp(Sdes)}${fp(Smax)}${fp(STdes,10)}${fp(pc,8)}   ${verdict}`);
  }

  if (morris) {
    console.error(`\nMorris screening (mu* rank for MAP; * = high interaction sigma/mu*>1):`);
    const m = morris.result.morris.map;
    if (m) console.error("  " + m.map(e=>e).sort((a,b)=>b.muStar-a.muStar).slice(0,8).map(e=>`${e.param}=${f(e.muStar,1)}${e.sigma>e.muStar?"*":""}`).join("  "));
  }
  summary[s] = rec;
}

fs.writeFileSync(new URL("./results/_summary.json", import.meta.url).pathname, JSON.stringify(summary, null, 2));
console.error(`\nwrote results/_summary.json`);

// --md : emit markdown one-lever validation tables (paste into the thesis section)
if (process.argv.includes("--md")) {
  let md = `## SA one-lever validation tables (auto-generated by scripts/sa/summarize.mjs)\n`;
  for (const s of points) {
    const rec = summary[s]; if (!rec) continue;
    md += `\n### ${s}\n\n`;
    if (rec.identifiability) md += `*FIM condition number ${rec.identifiability.condition.toExponential(2)}; identifiability order (column-pivoted QR): ${rec.identifiability.qrOrder.map(q=>q.param).join(" > ")}.*\n\n`;
    md += `| Target | Designated lever | Sᵢ | S_Tᵢ | Interaction (S_Tᵢ−Sᵢ) | Dominant? | PRCC | Verdict |\n`;
    md += `|---|---|---|---|---|---|---|---|\n`;
    for (const t of targets) {
      const r = rec.targets[t]; if (!r) continue;
      const sb = r.sobol || {};
      const ci = sb.CI ? ` (${sb.CI[0].toFixed(2)}–${sb.CI[1].toFixed(2)})` : "";
      md += `| ${t} | ${r.designated} | ${num(sb.Si)}${ci} | ${num(sb.STi)} | ${num(sb.interaction)} | ${sb.isMax===undefined?"·":(sb.isMax?"yes":"no ("+sb.SiMaxParam+")")} | ${num(r.prcc)} | ${r.verdict||"·"} |\n`;
    }
  }
  const p = new URL("./results/_thesis_tables.md", import.meta.url).pathname;
  fs.writeFileSync(p, md);
  console.error(`wrote ${p}`);
}
function num(x) { return Number.isFinite(x) ? x.toFixed(3) : "·"; }

function f(x, n = 0) { return Number.isFinite(x) ? x.toFixed(n) : "·"; }
function fp(x, w = 9, n = 2) { return (Number.isFinite(x) ? x.toFixed(n) : "·").padStart(w); }
